# Generated by Django 3.2.17 on 2023-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='lieu_arrivee',
            field=models.CharField(choices=[('Alger', 'Alger'), ('Oran', 'Oran'), ('Constantine', 'Constantine'), ('Annaba', 'Annaba'), ('Tlemcen', 'Tlemcen'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Béjaïa', 'Béjaïa'), ('Blida', 'Blida'), ('Sétif', 'Sétif'), ('Biskra', 'Biskra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='lieu_depart',
            field=models.CharField(choices=[('Alger', 'Alger'), ('Oran', 'Oran'), ('Constantine', 'Constantine'), ('Annaba', 'Annaba'), ('Tlemcen', 'Tlemcen'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Béjaïa', 'Béjaïa'), ('Blida', 'Blida'), ('Sétif', 'Sétif'), ('Biskra', 'Biskra')], max_length=100),
        ),
    ]
