# Generated by Django 3.2.17 on 2023-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
