# Generated by Django 3.2.17 on 2023-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0002_auto_20230921_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
