# Generated by Django 3.2.17 on 2023-09-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0004_price_product_producttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
