# Generated by Django 3.2.17 on 2023-09-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0006_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='reservation',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='trajet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trajets.trajet'),
        ),
    ]
