# Generated by Django 3.2.17 on 2023-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0007_auto_20230926_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
