# Generated by Django 3.2.17 on 2023-09-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trajets', '0008_alter_paymenthistory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trajets.passager'),
        ),
    ]
